# Prepare dataset

In [71]:
import pandas as pd
df=pd.read_csv("stock.csv",sep="|",names=["ident","name","price","unit","promotion","group","amount"])
df.head()

,ident,name,price,unit,promotion,group,amount
0,10000,Granny Smith Apples Loose,0.32,pieces,None,None,6.00
1,10001,Watermelon Fingers 90G,0.50,pieces,get4pay3,1,17.00
2,10002,Mango And Pineapple Fingers 80G,0.50,pieces,get4pay3,1,2.00
3,10003,Melon Finger Tray 80G,0.50,pieces,get4pay3,1,10.00
4,10004,Bananas Loose,0.68,kg,None,None,2.21

In [75]:
f=df.sort_values(by=['promotion','group','price'])
f

,ident,name,price,unit,promotion,group,amount
0,10000,Granny Smith Apples Loose,0.32,pieces,None,None,6.00
4,10004,Bananas Loose,0.68,kg,None,None,2.21
11,10011,Greek Feta 200G,1.20,pieces,None,None,23.00
5,10005,Conference Pears Loose,2.00,kg,None,None,1.55
21,10021,Cooked Mussels 580G,4.00,pieces,None,None,10.00
10,10010,British Mature Cheddar 450G,5.00,pieces,None,None,13.00
19,10019,Counter Haddock Fillet,5.50,kg,None,None,1.10
20,10020,Counter Cod Loin,13.50,kg,None,None,0.60
18,10018,Counter Tuna Steak,17.00,kg,None,None,2.14
13,10013,Emmental Slices 250G,1.75,pieces,get2pay1,None,9.00
12,10012,British Mature 10 Cheddar 250G,2.00,pieces,get2pay1,None,4.00
1,10001,Watermelon Fingers 90G,0.50,pieces,get4pay3,1,17.00
2,10002,Mango And Pineapple Fingers 80G,0.50,pieces,get4pay3,1,2.00
3,10003,Melon Finger Tray 80G,0.50,pieces,get4pay3,1,10.00
6,10006,Baby Corn 190G,1.40,pieces,get4pay3,2,19.00
7,10007,Carrot Batons 600G,1.00,pieces,get4pay3,3,5.00
9,10009,Asparagus Bundles 250G,1.10,pieces,get4pay3,3,8.00
8,10008,Maris Piper Mashed Potato 425G,1.25,pieces,get4pay3,3,11.00
17,10017,Brisket Beef 400G,3.50,pieces,get4pay3,4,15.00
16,10016,Sirloin Steak In Horseradish,3.75,pieces,get4pay3,4,14.00
14,10014,Beef Steak Mince 600G,4.00,pieces,get4pay3,4,3.21
15,10015,Diced Beef 400G,4.50,pieces,get4pay3,4,14.00

In [112]:
df.dtypes

ident          int64
name          object
price        float64
unit          object
promotion     object
group         object
amount       float64
dtype: object

In [113]:

df["name"]= df["name"].astype(str)
df["unit"]= df["unit"].astype(str)
df["promotion"]= df["promotion"].astype(str)
df["group"]= df["group"].astype(str)

In [114]:
df.to_csv("stock_data", index=False,header=0)

# Task 1. Load stock data: loadStockFromFile(filename)

In [94]:
import csv
def loadStockFromFile(filename="stock.csv"):
    
    stock_data=csv.reader(open(filename,'r',encoding='utf-8'))
    stock={}
 
    for item in stock_data:
        ident=item[0]
        name=item[1]
        price=float(item[2])
        unit=item[3]
        promotion=item[4]
        group=item[5]
        amount=float(item[6])
        
        stock[ident]={"name":name,
                      "price":price,
                      "unit":unit,
                      "promotion":promotion,
                      "group":group,
                      "amount":amount}
    return stock

In [95]:
stock=loadStockFromFile(filename="stock_data")

In [96]:
print(stock)

{'10000': {'name': 'Granny Smith Apples Loose', 'price': 0.32, 'unit': 'pieces', 'promotion': 'None', 'group': 'None', 'amount': 6.0}, '10001': {'name': 'Watermelon Fingers 90G', 'price': 0.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '1', 'amount': 17.0}, '10002': {'name': 'Mango And Pineapple Fingers 80G', 'price': 0.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '1', 'amount': 2.0}, '10003': {'name': 'Melon Finger Tray 80G', 'price': 0.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '1', 'amount': 10.0}, '10004': {'name': 'Bananas Loose', 'price': 0.68, 'unit': 'kg', 'promotion': 'None', 'group': 'None', 'amount': 2.21}, '10005': {'name': 'Conference Pears Loose', 'price': 2.0, 'unit': 'kg', 'promotion': 'None', 'group': 'None', 'amount': 1.55}, '10006': {'name': 'Baby Corn 190G', 'price': 1.4, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '2', 'amount': 19.0}, '10007': {'name': 'Carrot Batons 600G', 'price': 1.0, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '3', 'amount': 5.0}, '10008': {'name': 'Maris Piper Mashed Potato 425G', 'price': 1.25, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '3', 'amount': 11.0}, '10009': {'name': 'Asparagus Bundles 250G', 'price': 1.1, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '3', 'amount': 8.0}, '10010': {'name': 'British Mature Cheddar 450G', 'price': 5.0, 'unit': 'pieces', 'promotion': 'None', 'group': 'None', 'amount': 13.0}, '10011': {'name': 'Greek Feta 200G', 'price': 1.2, 'unit': 'pieces', 'promotion': 'None', 'group': 'None', 'amount': 23.0}, '10012': {'name': 'British Mature 10 Cheddar 250G', 'price': 2.0, 'unit': 'pieces', 'promotion': 'get2pay1', 'group': 'None', 'amount': 4.0}, '10013': {'name': 'Emmental Slices 250G', 'price': 1.75, 'unit': 'pieces', 'promotion': 'get2pay1', 'group': 'None', 'amount': 9.0}, '10014': {'name': 'Beef Steak Mince 600G', 'price': 4.0, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 3.21}, '10015': {'name': 'Diced Beef 400G', 'price': 4.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 14.0}, '10016': {'name': 'Sirloin Steak In Horseradish', 'price': 3.75, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 14.0}, '10017': {'name': 'Brisket Beef 400G', 'price': 3.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 15.0}, '10018': {'name': 'Counter Tuna Steak', 'price': 17.0, 'unit': 'kg', 'promotion': 'None', 'group': 'None', 'amount': 2.14}, '10019': {'name': 'Counter Haddock Fillet', 'price': 5.5, 'unit': 'kg', 'promotion': 'None', 'group': 'None', 'amount': 1.1}, '10020': {'name': 'Counter Cod Loin', 'price': 13.5, 'unit': 'kg', 'promotion': 'None', 'group': 'None', 'amount': 0.6}, '10021': {'name': 'Cooked Mussels 580G', 'price': 4.0, 'unit': 'pieces', 'promotion': 'None', 'group': 'None', 'amount': 10.0}}

# Task 2.Table of items on stock or in the basket:listItems(dct)

In [97]:
from collections import OrderedDict  
from tabulate import tabulate  

def listItems(stock):

        ans = []

        for item in sorted(stock):
                temp = []
                temp.append(item)
                temp.append(stock[item]['name'])
                temp.append(stock[item]['price'])
                temp.append(stock[item]['amount'])
                ans.append(temp)

        print(tabulate(ans,headers=['IDENT','PRODUCT','PRICE','AMOUNT'],tablefmt='orgtbl'))

In [98]:
listItems(stock)

|   IDENT | PRODUCT                         |   PRICE |   AMOUNT |
|---------+---------------------------------+---------+----------|
|   10000 | Granny Smith Apples Loose       |    0.32 |     6    |
|   10001 | Watermelon Fingers 90G          |    0.5  |    17    |
|   10002 | Mango And Pineapple Fingers 80G |    0.5  |     2    |
|   10003 | Melon Finger Tray 80G           |    0.5  |    10    |
|   10004 | Bananas Loose                   |    0.68 |     2.21 |
|   10005 | Conference Pears Loose          |    2    |     1.55 |
|   10006 | Baby Corn 190G                  |    1.4  |    19    |
|   10007 | Carrot Batons 600G              |    1    |     5    |
|   10008 | Maris Piper Mashed Potato 425G  |    1.25 |    11    |
|   10009 | Asparagus Bundles 250G          |    1.1  |     8    |
|   10010 | British Mature Cheddar 450G     |    5    |    13    |
|   10011 | Greek Feta 200G                 |    1.2  |    23    |
|   10012 | British Mature 10 Cheddar 250G  |    2    |     4    |
|   10013 | Emmental Slices 250G            |    1.75 |     9    |
|   10014 | Beef Steak Mince 600G           |    4    |     3.21 |
|   10015 | Diced Beef 400G                 |    4.5  |    14    |
|   10016 | Sirloin Steak In Horseradish    |    3.75 |    14    |
|   10017 | Brisket Beef 400G               |    3.5  |    15    |
|   10018 | Counter Tuna Steak              |   17    |     2.14 |
|   10019 | Counter Haddock Fillet          |    5.5  |     1.1  |
|   10020 | Counter Cod Loin                |   13.5  |     0.6  |
|   10021 | Cooked Mussels 580G             |    4    |    10    |

# Task 3.Search the stock:searchStock(stock,s)

In [99]:
import re
def searchStock(stock,s):
        
        res={}

        for item in stock:
                name=stock[item]['name']
                if re.search(s,name,re.IGNORECASE):
                    res[item]=stock[item]

        return res

In [100]:
searchStock(stock,s="Beef")

{'10014': {'name': 'Beef Steak Mince 600G',
  'price': 4.0,
  'unit': 'pieces',
  'promotion': 'get4pay3',
  'group': '4',
  'amount': 3.21},
 '10015': {'name': 'Diced Beef 400G',
  'price': 4.5,
  'unit': 'pieces',
  'promotion': 'get4pay3',
  'group': '4',
  'amount': 14.0},
 '10017': {'name': 'Brisket Beef 400G',
  'price': 3.5,
  'unit': 'pieces',
  'promotion': 'get4pay3',
  'group': '4',
  'amount': 15.0}}

# Task 4. Add or remove items: addToBasket(stock, basket, ident, amount)

In [101]:
def addToBasket(stock,basket,ident,amount):
    item=stock[ident]
    msg=None

    if(amount>=0):
        
        # option1
        
        if amount <= stock[ident]['amount']:
            stock[ident]['amount'] = stock[ident]['amount'] - amount            
            if ident in basket.keys():
                basket[ident]['amount'] = basket[ident]['amount'] + amount
            else :
                basket[ident]=item
                basket[ident]['amount']=amount
                  
            msg = None   
        #option2
        else :

            msg = "Cannot add this many " + stock[ident]['unit'] + " to the basket, only added " + str(stock[ident]['amount']) + " " + stock[ident]['unit'] + " ."

            basket[ident]['amount'] = basket[ident]['amount'] + stock[ident]['amount']
            stock[ident]['amount'] = 0
            
    else:
        #option3
        
        if amount <= basket[ident]['amount'] :
            stock[ident]['amount'] = stock[ident]['amount'] + amount
            basket[ident]['amount'] = basket[ident]['amount'] - amount
                        
            if basket[ident]['amount']==0:
                basket.pop(ident)
                                          
            msg = None
            
        #option4    
        else :

            msg = "Cannot remove this many " + basket[ident]['unit'] + " from the basket, only removed" + str(basket[ident]['amount']) + " " + basket[ident]['unit'] + " ."

            stock[ident]['amount'] = stock[ident]['amount'] + basket[ident]['amount']
            basket[ident]['amount'] = 0
            
    
    return msg


# Task 5: Prepare for checkout: prepareCheckout(basket)

In [102]:
def prepareCheckout(basket):
    for item in basket:
        basket[item]["amountPayable"]=basket[item]["amount"]
        
    return basket

# Task 6: Produce a bill getBill(basket) (without promotions)

In [103]:
def getBill(basket):

        ans = []

        payable_final=0
        for item in sorted(basket):
                temp = []
                temp.append(basket[item]['name'])
                temp.append(basket[item]['price'])
                temp.append(basket[item]['amount'])
                payable=float(basket[item]['amount']*basket[item]['price'])
                temp.append(payable)
                payable_final = payable_final + payable
                ans.append(temp)

        temp=[]
        temp.append("Total")
        temp.append("")
        temp.append("")
        temp.append(payable_final)

        ans.append(temp)

        print(tabulate(ans,headers=['PRODUCT','PRICE','AMOUNT','PAYABLE'],tablefmt='orgtbl'))

# Task 7: The main() function

In [104]:
# def main():
    
#     stock = loadStockFromFile('stock_data.csv')
#     basket = { }
#     print("*"*75)
#     print("*"*15+" "*10+"WELCOME TO STEFAN EXPRESS"+" "*10+"*"*15)
#     print("*"*75,"\n")

#     while True:
#         s = input("Input product-Ident, search string, 0 to display basket, 1 to check out: ")
#         # TODO: complete the code
#         if s==0:
#             listItems(basket)
#         if s==1:
#             prepareCheckout(basket)

In [105]:
if __name__== "__main__":

        # Task 1. Loading stock in dictionary from the csv file
        
        stock=loadStockFromFile("stock_data")
        # print("Printing the stock ->")
        # listItems(stock)
        # print(stock)

        # initializing the basket
        basket={}

        # Task 2. Lisiting the items in stock or basket
        print("\nList items in stock ->\n")
        listItems(stock)
        # print(items)

        # Task 3. Searching in the stock
        ans=searchStock(stock,"bee")
        print("\nSearch Result")
        print(ans)

        # Task 4. Adding items from stock to the basket
        msg = addToBasket(stock,basket,'10005',1)
        print(msg)
        msg = addToBasket(stock,basket,'10013',3)
        print(msg)
        msg = addToBasket(stock,basket,'10015',5)
        msg = addToBasket(stock,basket,'10017',3)


        # sorting the basket according to the ident
        basket=OrderedDict(sorted(basket.items()))

        # Task 5. Preparing for Checkout i.e. adding a key - amountPayable to basket
        print("\nPreparing for Checkout\n")
        prepareCheckout(basket)

        # Task 6. Getting the Bill of the basket
        print("\n*******************   Bill   *********************\n")
        getBill(basket)

List items in stock ->

|   IDENT | PRODUCT                         |   PRICE |   AMOUNT |
|---------+---------------------------------+---------+----------|
|   10000 | Granny Smith Apples Loose       |    0.32 |     6    |
|   10001 | Watermelon Fingers 90G          |    0.5  |    17    |
|   10002 | Mango And Pineapple Fingers 80G |    0.5  |     2    |
|   10003 | Melon Finger Tray 80G           |    0.5  |    10    |
|   10004 | Bananas Loose                   |    0.68 |     2.21 |
|   10005 | Conference Pears Loose          |    2    |     1.55 |
|   10006 | Baby Corn 190G                  |    1.4  |    19    |
|   10007 | Carrot Batons 600G              |    1    |     5    |
|   10008 | Maris Piper Mashed Potato 425G  |    1.25 |    11    |
|   10009 | Asparagus Bundles 250G          |    1.1  |     8    |
|   10010 | British Mature Cheddar 450G     |    5    |    13    |
|   10011 | Greek Feta 200G                 |    1.2  |    23    |
|   10012 | British Mature 10 Cheddar 250G  |    2    |     4    |
|   10013 | Emmental Slices 250G            |    1.75 |     9    |
|   10014 | Beef Steak Mince 600G           |    4    |     3.21 |
|   10015 | Diced Beef 400G                 |    4.5  |    14    |
|   10016 | Sirloin Steak In Horseradish    |    3.75 |    14    |
|   10017 | Brisket Beef 400G               |    3.5  |    15    |
|   10018 | Counter Tuna Steak              |   17    |     2.14 |
|   10019 | Counter Haddock Fillet          |    5.5  |     1.1  |
|   10020 | Counter Cod Loin                |   13.5  |     0.6  |
|   10021 | Cooked Mussels 580G             |    4    |    10    |

Search Result
{'10014': {'name': 'Beef Steak Mince 600G', 'price': 4.0, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 3.21}, '10015': {'name': 'Diced Beef 400G', 'price': 4.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 14.0}, '10017': {'name': 'Brisket Beef 400G', 'price': 3.5, 'unit': 'pieces', 'promotion': 'get4pay3', 'group': '4', 'amount': 15.0}}
None
None

Preparing for Checkout


*******************   Bill   *********************

| PRODUCT                | PRICE   | AMOUNT   |   PAYABLE |
|------------------------+---------+----------+-----------|
| Conference Pears Loose | 2.0     | 1        |      2    |
| Emmental Slices 250G   | 1.75    | 3        |      5.25 |
| Diced Beef 400G        | 4.5     | 5        |     22.5  |
| Brisket Beef 400G      | 3.5     | 3        |     10.5  |
| Total                  |         |          |     40.25 |

# Task 8: Applying promotions applyPromotions(basket)

In [106]:
def applyPromotions(basket):
    import math
    group1={}
    group2={}
    group3={}
    group4={}
    groupNone={}
    final={}
         
    for item in basket:
        if basket[item]['promotion'] == "get2pay1":
            p=math.ceil(basket[item]['amount']/2)
            basket[item]["amountPayable"]=p
            final[item]=basket[item]
                        
        elif basket[item]['promotion'] == "get4pay3":
            
            if basket[item]['group']=="1":
                group1[item]=basket[item]
            elif basket[item]['group']=="2":
                group2[item]=basket[item]
            elif basket[item]['group']=="3":
                group3[item]=basket[item]
            elif basket[item]['group']=="4":
                group4[item]=basket[item]            
            elif basket[item]['group']=="None":
                groupNone[item]=basket[item]
                
        elif basket[item]['promotion'] == "None":
            final[item]=basket[item]
                        
    def applyOnGroup(group):
        totalAmount=0
        for item in group:
            totalAmount=totalAmount + group[item]['amount']
        
        removeAmount=totalAmount//4
#         paidAmount=totalAmount-removeAmount
            

        group = dict(sorted(group.items(), key = lambda x: x[1]['price']))
                        
        for item in group:
            if group[item]["amount"] >= removeAmount:
                group[item]['amountPayable']=group[item]['amount']-removeAmount
                removeAmount=0
                break
            else:
                removeAmount=removeAmount-group[item]['amount']
                group[item]['amountPayable']=0
        return group
    

  
    group1=applyOnGroup(group1)
    
    for item in group1:
        final[item]=group1[item]
        
    group2=applyOnGroup(group2)
        
    for item in group2:
        final[item]=group2[item]
        
    group3=applyOnGroup(group3)
    
    for item in group3:
        final[item]=group3[item]
        
    group4=applyOnGroup(group4)
    
    for item in group4:
        final[item]=group4[item]
        
    groupNone=applyOnGroup(groupNone)
        
    for item in groupNone:
        final[item]=groupNone[item]
    

        
    return final

In [149]:
def sortdict(basket):
    import pandas as pd
    df=pd.DataFrame.from_dict(basket,orient='index')
#     print(df.columns)
   
    f=df.sort_values(by=['promotion','group','price'])
#     print(f.index.values)
    basket=f.to_dict('series')
    for i in  basket:
        print(i+"h")
    return basket

In [150]:
sortdict(basket)

nameh
priceh
unith
promotionh
grouph
amounth
amountPayableh

{'name': 10005    Conference Pears Loose
 10013      Emmental Slices 250G
 10017         Brisket Beef 400G
 10015           Diced Beef 400G
 Name: name, dtype: object,
 'price': 10005    2.00
 10013    1.75
 10017    3.50
 10015    4.50
 Name: price, dtype: float64,
 'unit': 10005        kg
 10013    pieces
 10017    pieces
 10015    pieces
 Name: unit, dtype: object,
 'promotion': 10005        None
 10013    get2pay1
 10017    get4pay3
 10015    get4pay3
 Name: promotion, dtype: object,
 'group': 10005    None
 10013    None
 10017       4
 10015       4
 Name: group, dtype: object,
 'amount': 10005    1
 10013    3
 10017    3
 10015    5
 Name: amount, dtype: int64,
 'amountPayable': 10005    1
 10013    3
 10017    3
 10015    5
 Name: amountPayable, dtype: int64}

In [108]:
basket=applyPromotions(basket)

NameError: name 'math' is not defined

In [237]:
basket

{'10005': {'name': 'Conference Pears Loose',
  'price': 2.0,
  'unit': 'kg',
  'promotion': 'None',
  'group': 'None',
  'amount': 1,
  'amountPayable': 1},
 '10013': {'name': 'Emmental Slices 250G',
  'price': 1.75,
  'unit': 'pieces',
  'promotion': 'get2pay1',
  'group': 'None',
  'amount': 3,
  'amountPayable': 2},
 '10017': {'name': 'Brisket Beef 400G',
  'price': 3.5,
  'unit': 'pieces',
  'promotion': 'get4pay3',
  'group': '4',
  'amount': 3,
  'amountPayable': 1},
 '10015': {'name': 'Diced Beef 400G',
  'price': 4.5,
  'unit': 'pieces',
  'promotion': 'get4pay3',
  'group': '4',
  'amount': 5,
  'amountPayable': 5}}

In [247]:
# adjust getbill function
def getBillAdjust(basket):

        ans = []

        payable_final=0
        for item in sorted(basket):
                temp = []
                temp.append(basket[item]['name'])
                temp.append(basket[item]['price'])
                temp.append(basket[item]['amount'])
                temp.append(basket[item]['amountPayable'])
                payable=float(basket[item]['amount']*basket[item]['price'])
                temp.append(payable)
                payable_final = payable_final + payable
                ans.append(temp)

        temp=[]
        temp.append("Total")
        temp.append("")
        temp.append("")
        temp.append("")
        temp.append(payable_final)

        ans.append(temp)

        print(tabulate(ans,headers=['PRODUCT','PRICE','AMOUNT','amountPayable','PAYABLE'],tablefmt='orgtbl'))
        print("**********     THANK YOU FOR SHOPPING AT STEFAN EXPRESS!     ***********")

In [248]:
getBillAdjust(basket)

| PRODUCT                | PRICE   | AMOUNT   | amountPayable   |   PAYABLE |
|------------------------+---------+----------+-----------------+-----------|
| Conference Pears Loose | 2.0     | 1        | 1               |      2    |
| Emmental Slices 250G   | 1.75    | 3        | 2               |      5.25 |
| Diced Beef 400G        | 4.5     | 5        | 5               |     22.5  |
| Brisket Beef 400G      | 3.5     | 3        | 1               |     10.5  |
| Total                  |         |          |                 |     40.25 |
**********     THANK YOU FOR SHOPPING AT STEFAN EXPRESS!     ***********